on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up Gleam
        id: setup-gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      - name: Install dependencies
        run: gleam deps download
      - name: Build app
        run: gleam run -m lustre/dev build app
      - name: Replace placeholder in index.html
        run: sed -i 's/Lustre SPA deployment demo/Lustre SPA deployment demo (Cloudflare Pages)/' index.html
      - name: Copy output to dist
        run: mkdir dist && cp index.html dist/index.html && cp -r priv dist/priv
      - name: Deploy with Wrangler
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name lustre-spa-deployment
        if: github.ref == 'refs/heads/main'
